### ISSUE TITLE
Make list of AV needs for event

### ISSUE THREAD

**Issue by BluesGuy** [codefordenver/CodeAcross-2015#10]
Projectors, PA, microphones, etc

**Comment by BluesGuy** [comment]
- Projector (do we need more than 1?)
- PA system
- Mics (how many)
- Adaptors (Mac to projector, Win laptop to projector)

**Comment by biodavis** [comment]
Flip charts with markers
white boards with markers
name tags

**Comment by wdoug** [comment]
I don't think we will need a projector since we can hook into the main tv's in the Galvanize Atrium.
