### ISSUE TITLE
Market Event

### ISSUE THREAD

**Issue by wdoug** [codefordenver/CodeAcross-2015#12]
- Who is the audiences we are trying to attract

**Comment by cdoelling** [comment]
Reach out to:

BuiltinColorado Events
Galvanize Events
Denver Post
Westword
Denver Voice
Go Code People

**Comment by wdoug** [comment]
Harry reached out to DU

**Comment by wdoug** [comment]
Some folks from Mines said they would promote the event to their department.

**Comment by wdoug** [comment]
Some folks from Mines said they would promote the event to their department.

**Comment by wdoug** [comment]
I will reach out to Horace at Turing.

**Comment by wdoug** [comment]
Spreadsheet https://docs.google.com/spreadsheets/d/1JtcGb3GfFvZTpXi1U7kIdsnYUT1SfxFEC-eQU0x512o/edit#gid=0

**Comment by wdoug** [comment]
Finish press release

**Comment by ondrae** [comment]
It looks like you had a very fun CodeAcross back in Feb with good comments on the Meetup. Its also cool seeing you do your event planning on GitHub and Waffle.

All these comments can be closed now though right? Just doing a little open source gardening of Brigade  projects.

**Comment by dviramontes** [comment]
@ondrae correct, thanks!
