### ISSUE TITLE
Media Relations - day of

### ISSUE THREAD

**Issue by BluesGuy** [codefordenver/CodeAcross-2015#2]

**Comment by BluesGuy** [comment]
-  Develop list of media outlets to keep apprised of progress.  Ideally, engage someone in the media community.
-  Develop media communication plan (schedule, etc)
-  See who has contacts at various outlets (Westword, Denver Post, TV stations, radio??,   What about web outlets?

**Comment by wdoug** [comment]
Two of my friends may be willing to do some filming at CodeAcross. They should be able to stop by Galvanize at some point the evening of Feb. 9th
