### ISSUE TITLE
Clarify appropriate problem statements with each nonprofit in advance of event

### ISSUE THREAD

**Issue by fishfade** [codefordenver/CodeAcross-2015#33]

**Comment by vzolyak** [comment]
Rachel and Willy - I'd like to help with this.  Please let me know what I can do to help

**Comment by karenderrickdavis** [comment]
I will send formal intros to Rocky Mtn Farmers Union and SAME this evening.

**Comment by dviramontes** [comment]
coavp intro email sent

**Comment by wdoug** [comment]
Met with Brendon of RMMFI on Friday
