### ISSUE TITLE
Non-Profit identification

### ISSUE THREAD

**Issue by BluesGuy** [codefordenver/CodeAcross-2015#4]
- Establish the criteria for which non-profits we will want to invite
- Vet which non-profits would be appropriate for our group to partner with

**Comment by wdoug** [comment]
We will need to figure out what we can offer to these non-profits to invite them

**Comment by BluesGuy** [comment]
Agreed.  As I understand it, we are offering an experienced development team to implement and launch a project mutually defined by the NP and CAD, that can be delivered within 3 months of the event.  What the project is, would depend on the needs of the NP.  We currently have expertise in web development, database design, and data analysis.  

That's what I understand we're offering - free project-focused, development and delivery

On Tuesday, December 2, 2014 8:36 PM, Willy Douglas notifications@github.com wrote:

We will need to figure out what we can offer to these non-profits to invite them

**Comment by biodavis** [comment]
Added to the issue (above) shoudl be :  process for IDing the Non-profit and Process for inviting NP.

**Comment by biodavis** [comment]
Some Suggested  Criteria:
1) Denver Metro Area
2) NP has little or no budget for Software Development (SD)
3) Non-profit has good chance of success with project (this would be broken down into other criteria, in part based on interviews), but including
a) how long established, membership, funding, # of grants/money, mission vision, strategic plan.
4) Cannot be associated with any other Code for America plan party (eg, no conflict of interest)
5) Project can be leveraged by other NPs 
6) project will be open source (eg, not owned by the NP)
7)  After a number of NP have been IDed, another few questions (would require contact)
a) NP has point of contact that will work with us
b) NP can provide users/customers for agile development
c) NP has possibility to maintain code in future (eg, relationship with foundation for money in future).

**Comment by biodavis** [comment]
types or categories of Non-Profits:
•  Animals
•  Anti-Fracking
•  Arts & Culture
•  Breast Cancer
•  Bullying
•  Cancer
•  Children & Youth
•  Civil Rights
•  Climate Change
•  Crime & Law
•  Disabilities
•  Disaster Aid
•  Economic Development
•  Education
•  Environment
•  Food
•  Health
•  Homeless & Housing
•  Human Services
•  Human Trafficking
•  Immigration
•  International
•  International Exchange
•  Job Training
•  LGBTQ
•  Mental Health
•  Microfinance
•  Philanthropy
•  Race
•  Religion
•  Reproductive Rights
•  Seniors
•  Sports
•  Technology
•  Veterans
•  Water
•  Women

**Comment by wdoug** [comment]
Our current list of nonprofits to reach out to: https://docs.google.com/spreadsheets/d/1RJ0HpE9NmeLTmn57IDolqR_AWYab1TwDU0hYxf8fCyQ/edit#gid=0
