### ISSUE TITLE
Reach out to Computer science departments

### ISSUE THREAD

**Issue by wdoug** [codefordenver/CodeAcross-2015#48]
For audience and for potential members, reach out to Area universities Comp sci departments

**Comment by wdoug** [comment]
Brian is planning on working on this

**Comment by biodavis** [comment]
with Harry

**Comment by biodavis** [comment]
gSchool- David

**Comment by biodavis** [comment]
Turing- Willy to contact Horace

**Comment by biodavis** [comment]
Karen is reaching out to Jeff Macco

**Comment by dviramontes** [comment]
I reached out to Aaron from galvanize,
he basically said i should get in touch 
with gSchool directly.

will do that next, does anybody know
anyone at gSchool ? student or instructor ?

**Comment by dviramontes** [comment]
sent email to Krista (event organizer) from gSchool

**Comment by dviramontes** [comment]
added another iteration to the email template that you can probably use to send to these school departments:
[scroll to bottom]
https://docs.google.com/document/d/1wS0YIImTWVNug-7bgekRCfROMY0UA7XN_3Uaf3MXFtY/edit#

**Comment by biodavis** [comment]
Dinh Emailed University of Denver on Jan 15, to head of department to email all students

**Comment by biodavis** [comment]
Brian Emailed UC Denver Head of Comp Sci Dept. Feb 9

**Comment by biodavis** [comment]
Brian Emailed 5 departments at Regis University on Feb 9

**Comment by biodavis** [comment]
Brian emailed 2 at Colorado School of Mines Feb 9

**Comment by biodavis** [comment]
Brian Emailed Metro state (Dr. Tucker) Feb 9

**Comment by biodavis** [comment]
Brian Emailed Eric Hamilton at Community College of Denver

**Comment by biodavis** [comment]
Feb 10:  very nice email back from Colorado School of Mines:Kevin Moore, Dean, incl rhaupt@mines.edu,
Juan Carlos Lucena jlucena@mines.edu,
Mark Mondry mmondry@mines.edu,
Jered Dean jdean@mines.edu
THey are communicating with up to 400 students and Juan Carols will be coming to the event.

**Comment by biodavis** [comment]
Non-committal answer from Denver Community College (Eric Hamilton).

**Comment by biodavis** [comment]
Nice email form Rob Sjodin, from Regis, he will come to our event, too.
