### ISSUE TITLE
Event Day Food : Breakfast

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/CodeAcross-2015#49]

**Comment by wdoug** [comment]
Karen - Reach out to SAME about capacity

**Comment by wdoug** [comment]
Adam - look at Breakfast possibilities

**Comment by TinkurLab** [comment]
Brandon - determine bagel pricing from company's normal supplier

**Comment by Ditofry** [comment]
So for about $140 Einstein's will deliver 8dozen bagels and 16 containers of cream cheese.  We can order online and they're usually pretty snappy in terms of response time.

Einstein's lists their coffee and tea for groups as 14.99 per serving, which serves up to 10 people.

[Rosenburg's](http://rosenbergsbagels.com/) (Local shop with better bagels), will do the same thing but it costs about $180.  We would need to get in touch with the at least a day before hand.

**Comment by TinkurLab** [comment]
Moes is $144 for 8 dozen bagels + cream cheeses.

**Comment by wdoug** [comment]
How much does coffee cost from Moe's, and how much would we want to order?

**Comment by Ditofry** [comment]
@TinkurLab I can pick these up if you're not already planning to

**Comment by Ditofry** [comment]
Bagels are ordered, but I can't pick them up until 7am on saturday, so I'll probably show up around 7:20

**Comment by wdoug** [comment]
Sounds good. Thanks @Ditofry!

**Comment by dviramontes** [comment]
Thanks @Ditofry !!!
