### ISSUE TITLE
Sponsor identification and outreach

### ISSUE THREAD

**Issue by BluesGuy** [codefordenver/CodeAcross-2015#5]

**Comment by BluesGuy** [comment]
- What are the forms of sponsorship? (in-kind contribution, $$$, equipment, space, programs, etc)
- What do we need in terms of what sponsors can provide?

**Comment by wdoug** [comment]
Whole foods could be good - needs lead time of about 4 weeks?

**Comment by wdoug** [comment]
Since we have not been successful yet, in order to not waste focus, we will be relying on funding from CfA, and potentially Rally.
